name: Deploy ArcGIS Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]

permissions:
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          allow-no-subscriptions: false
        env:
          AZURE_CORE_SURVEY_DISABLE: true
          AZURE_CORE_COLLECT_TELEMETRY: false

      - name: Create Resource Group
        run: |
          az group create \
            --name rg-simple-func-iac-arcgis \
            --location westeurope \
            --output none

      - name: Test Azure CLI Connection
        run: |
          az account show --output table
          az group list --output table

      - name: Deploy ArcGIS Infrastructure with Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: 2.72.0
          inlineScript: |
            echo "=== Starting ArcGIS infrastructure deployment ==="
            az deployment group create \
              --resource-group rg-simple-func-iac-arcgis \
              --template-file infra/main.bicep \
              --parameters \
                functionAppName='simple-func-iac-arcgis-ba' \
                storageAccountName='sfiacarcgis' \
                appInsightsName='simple-func-iac-arcgis-ba-insights' \
                hostingPlanName='simple-func-iac-arcgis-ba-plan' \
                arcgisUrl='https://www.arcgis.com' \
                arcgisUsername='${{ secrets.ARCGIS_USERNAME }}' \
                arcgisPassword='${{ secrets.ARCGIS_PASSWORD }}' \
                featureServiceId='${{ secrets.FEATURE_SERVICE_ID }}' \
                featureLayerIndex='${{ secrets.FEATURE_LAYER_INDEX }}' \
              --name arcgis-infrastructure-deployment \
              --mode Incremental \
              --verbose
        env:
          AZURE_CORE_SURVEY_DISABLE: true
          AZURE_CORE_COLLECT_TELEMETRY: false

      - name: Get Deployment Outputs
        id: get-outputs
        run: |
          FUNCTION_APP_NAME=$(az deployment group show \
            --resource-group rg-simple-func-iac-arcgis \
            --name arcgis-infrastructure-deployment \
            --query properties.outputs.functionAppName.value \
            --output tsv)
          echo "function-app-name=$FUNCTION_APP_NAME" >> $GITHUB_OUTPUT

      - name: Show Deployment Results
        run: |
          echo "=== ArcGIS Infrastructure Deployment Completed Successfully ==="
          FUNCTION_APP_NAME=$(az deployment group show \
            --resource-group rg-simple-func-iac-arcgis \
            --name arcgis-infrastructure-deployment \
            --query properties.outputs.functionAppName.value \
            --output tsv)
          FUNCTION_APP_URL=$(az deployment group show \
            --resource-group rg-simple-func-iac-arcgis \
            --name arcgis-infrastructure-deployment \
            --query properties.outputs.functionAppUrl.value \
            --output tsv)
          STORAGE_ACCOUNT_NAME=$(az deployment group show \
            --resource-group rg-simple-func-iac-arcgis \
            --name arcgis-infrastructure-deployment \
            --query properties.outputs.storageAccountName.value \
            --output tsv)
          APP_INSIGHTS_NAME=$(az deployment group show \
            --resource-group rg-simple-func-iac-arcgis \
            --name arcgis-infrastructure-deployment \
            --query properties.outputs.appInsightsName.value \
            --output tsv)
          
          echo "Function App Name: $FUNCTION_APP_NAME"
          echo "Function App URL: $FUNCTION_APP_URL"
          echo "Storage Account: $STORAGE_ACCOUNT_NAME"
          echo "App Insights: $APP_INSIGHTS_NAME"
          echo "=== Next Steps ==="
          echo "1. Run the 'Deploy ArcGIS Function App' workflow to deploy the function code"
          echo "2. Test the ArcGIS endpoints after deployment"